packages:
  - 'frontend'
  - 'backend'

overrides:
  'codemirror': '6.0.1'
  'zod': '3.25.76'
  '@types/react': '18.3.3'
  'typescript': '5.5.4'

allowBuilds:
  '@firebase/util': true
  '@swc/core': true
  'better-sqlite3': true
  'core-js-pure': true
  'esbuild': true
  'protobufjs': true
  'sharp': true